Add supercollider server status notification
scztt/LanguageServer.quark pull request #26
Opened 2024-05-28 20:53 UTC by jenshaase

Hi,

I added a new custom notification to the LSP. This notification will send status information about the Supercollider Server to the LSP client.

Once this is merged I can create another MR for the VSCode extension to show the data in the StatusBar. Here is already a preview:

![grafik](https://github.com/scztt/LanguageServer.quark/assets/176220/ef6bf205-0f48-4bd2-b721-69c28364062c)

2024-05-30 17:02 UTC, scztt commented
Thanks for the PR jens! This is fantastic - I made a bunch of small nit-picky comments, but overall everything looks great, I'd love to get this merged.

2024-05-30 19:30 UTC, jenshaase commented
@scztt I cannot see the comments you added. Do I miss anything?

2024-05-30 20:48 UTC, scztt requested changes

2024-05-30 20:48 UTC, scztt commented on Notifications/ServerStatusNotification.sc
> +        var registerServer = { | server update |
I'd prefer to use an argument style like this (newline, commas, no spaces inside the |)
```
{
   |arg, arg, arg|
}
```
to match the rest of the codebase.

2024-05-30 20:48 UTC, scztt commented on Notifications/ServerStatusNotification.sc
> +	*serverCapabilityName { ^"serverStatus" }
Inconsistant formatting - I can do a pass with the sclang formatter before this is merged to normalize it with everything else, no need to worry about it unless you're also using the formatter.

2024-05-30 20:48 UTC, scztt commented on Notifications/ServerStatusNotification.sc
> +                \running: Server.default.serverRunning,
Prefixing keys with `\` is not required for Events.

2024-05-30 20:48 UTC, scztt commented on Notifications/ServerStatusNotification.sc
> +}
Missing an empty line at end of file.

2024-05-30 20:48 UTC, scztt commented on Notifications/ServerStatusNotification.sc
> +				.put(\serverAdded, { | serverClass what server | registerServer.value(server, true) });
Maybe we ditch the `update` argument, and just call `this.updateState(server)` here - it simplifies `registerServer` and reads more clearly.

2024-05-30 20:48 UTC, scztt commented on Notifications/ServerStatusNotification.sc
> +    updateState { |serverName|
In all our cases, we have access to the actual Server object - I think this can just be `|server|`, and the comparison can be `Server.default === server` - if we end up for some reason with Servers with duplicate names, this will still work.

2024-05-30 20:48 UTC, scztt commented on LSPFeature.sc
> +}
Add empty line.

2024-05-30 20:48 UTC, scztt commented on Notifications/ServerStatusNotification.sc
> +	*serverCapabilityName { ^"serverStatus" }
Oh, I realize this may actually be a bug case with the formatter also, it occasionally gets this kind of thing wrong - I need to fix that. If so, just a manual re-indent is fine.

2024-05-30 20:48 UTC, scztt commented on Notifications/ServerStatusNotification.sc
> +    options {
No need to do this in this PR, but we should consider sending back a list of the server metrics as part of our options, something like:
```
{
  "avgCPU": {
     "name": "Average CPU",
     "shortName": "avgCPU",
     "units": "%"
  },
  //...
}
```

That way, the client doesn't need to hard-code the list of metrics - they are fully supplied by the server, and all the client does is some string formatting and maybe let the user turn on/off the display of individual ones.

2024-05-30 20:48 UTC, scztt commented on Notifications/ServerStatusNotification.sc
> +            var params = (
Should we send back a server name as well? It would be useful to display, and it will definitely be required for multi-server setups in the future.

2024-05-30 20:48 UTC, scztt commented on Notifications/ServerStatusNotification.sc
> +                .put(\counts, { this.updateState(server.name) });
We should add `\didQuit` also, else we may not catch some cases where the server stops running?

2024-05-30 20:48 UTC, scztt commented
> @scztt I cannot see the comments you added. Do I miss anything?

Sorry, I think i did not submit them - can you see them now?

2024-05-30 20:56 UTC, jenshaase commented
@scztt I can see them now. Thanks.

2024-05-31 19:57 UTC, jenshaase commented on Notifications/ServerStatusNotification.sc
> +            var params = (
I added the server name as well.

2024-05-31 20:00 UTC, jenshaase commented on Notifications/ServerStatusNotification.sc
> +                .put(\counts, { this.updateState(server.name) });
I added it.

2024-05-31 20:01 UTC, jenshaase commented on Notifications/ServerStatusNotification.sc
> +    options {
I'll leave this open for now.

2024-05-31 20:01 UTC, jenshaase commented
@scztt I fixed this PR now.

2024-06-09 12:36 UTC, merged